### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by cserteGT3** [asprionj/LiveServer.jl#103]
The last commit on the `gh-pages` branch was in November 2019, but I could not find why the documentation job is "skipped" on travis.

**Comment by tlienart** [comment]
oh! thanks for noticing this; I'll look into it

**Comment by tlienart** [comment]
@asprionj in order to setup a GitHub action, would you mind giving me full admin access to this repo? otherwise (I'm not sure whether it's possible to give full admin access to someone else for someone's repo) would you mind follow the steps here: https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#GitHub-Actions should take 5 mins (to setup the keys) thanks!

**Comment by tlienart** [comment]
ok nvm, it's because travis has deprecated the use of both `matrix` and `jobs` and, as a result, `jobs` was not executed.

**Comment by cserteGT3** [comment]
Thanks for quickly fixing it!

**Comment by tlienart** [comment]
thanks for bringing it up :)
