### ISSUE TITLE
Test ws_tracker

### ISSUE THREAD

**Issue by tlienart** [asprionj/LiveServer.jl#38]
Ref #32

**Comment by asprionj** [comment]
Yeah since #36 this won't work anymore this way. I'm currently trying to get this working. The problem is that I cannot get the client connection working properly (with `HTTP.WebSockets.open`). The minimal server in the test works fine if I establish a websocket connection from a browser.

That means I have to (again) dig into the HTTP.jl code. For it to be titled the official HTTP-server-library I think HTTP.jl is very rough and above all, poorly documented.

**Comment by asprionj** [comment]
Seems to work, tests pass, bumping coverage up to 94% ;-)

**Comment by tlienart** [comment]
very nice! (and yeah I agree with the assessment for HTTP.jl it's a bit hard though because it looks from the outside as if there is currently no formal maintainer(s), just making PRs to get the docs better would already be very useful but we need someone to be able to review and merge our fixes... my PR is still without comments 😢

**Comment by tlienart** [comment]
Ok no so that test doesn't consistently pass unfortunately. It often fails with `KeyError: key "ws_TESTFILE.html" not found` yet works when done step by step... again some voodoo happening here.
