### ISSUE TITLE
Interplay with Documenter.jl

### ISSUE THREAD

**Issue by tlienart** [asprionj/LiveServer.jl#41]
I think it'd be nice to have LiveServer play nicely with Documenter.jl in that when you compile the docs you typically want to have a look at them too.

One thing to do (I'm working on it) is to make `serve` take an argument `dir` which can specify a directory to watch that is not the current one. That's not too hard just requires `get_fs_path` to use the root. 

Then we'd have to see how the two can play well together, I'm sure that would get some Julia folks interested.

**Comment by tlienart** [comment]
Ok I have a working prototype for this and it's quite nice. See `servedocs`.

**Comment by asprionj** [comment]
Had this (passing a `dir` to `serve`) in my mind since the beginning. Thought that we'd be starting to build a full-blown static server though, so I did not implement it right from the beginning. (Compare e.g. NGINX; you can configure it to server arbitrarily many directories at arbitrary URL paths.) 

Now that there's a cool use case, I think just being able to tell `serve` which directory to serve is a good thing.

**Comment by tlienart** [comment]
yay!
