### ISSUE TITLE
servedocs improvements

### ISSUE THREAD

**Issue by asprionj** [asprionj/LiveServer.jl#53]
- First suggestion: https://github.com/asprionj/LiveServer.jl/issues/43#issuecomment-481399735
- Then, we should add tests for it to get coverage up again.
- Should we move it to a separate file? It does not belong in the main module file `LiveServer.jl`, but somehow neither in `server.jl`...
- A nice feature would be that it automatically detects new files. For this, we could use the `coreloopfun` and a marginally modified `FileWatcher` with one additional field holding the path to the `docs` folder we're serving. This could be used in the loop-function (e.g. on every 10th call or so) to check for new files against `is_watched`.

This is your brainchild, so I let you decide what to do and what to leave. I'll help as time allows me to. ;-)

**Comment by tlienart** [comment]
With respect to your 3d point, I think there's now enough to have a `utils.jl` file which contains `example`, `verbose` and `servedocs`. 

I agree with the rest. Tests are somewhat artificial here since there's not much that's being done in the function that isn't tested by `serve` but I can check.

And yes for new files with coreloop. In fact that's pretty much why I use coreloop in JuDoc.
