### ISSUE TITLE
FileWatcher stops watching a file that still exists

### ISSUE THREAD

**Issue by briochemc** [asprionj/LiveServer.jl#88]
Sometimes when I save some edits on a file (using `:w` in vim) in order to see the corresponding doc file updated, the watcher tells me suddenly that 
```julia
ℹ [LiveUpdater]: Reacting to change in file 'XXX.jl'...
[ Info: [FileWatcher]: file 'XXX.jl' does not exist  (anymore); removing it from list of watched files.
```
and I have to restart LiveServer... 
In case it's relevant, I am using Literate.jl to generate the corresponding `XXX.md` file for the docs so maybe that's an issue?

I also guess one solution would be to disallow the file watcher to think files have disappeared? (I rarely delete files while editing docs.)

**Comment by tlienart** [comment]
Hmm that's odd, I'll need a bit more info to try to  work out what's going on but the proposal to avoid checking whether files have disappeared is not going to work because basically there's a check  `isfile(filepath)` and if that returns false and you still carry on, bad things will happen.

A  few questions to try to  clarify  what's going on:

- in the [liveserver+literate](https://asprionj.github.io/LiveServer.jl/stable/man/ls+lit/) docs, which folder structure do  you use?
- do you only get this _from time to time_ or does  it happen systematically
- have you tried using another editor to see if you get the same issue?

What's weird is  that the issue that you're getting means  that, at some point, julia does `isfile("path/to/XXX.jl")` and that returns `false` which triggers the warning you're seeing. I'm not aware of  anything in LS itself that could cause this. So  I'm inclined to think it may  be specific to  `vim` or your `make.jl` file is doing something strange (?).

**Comment by briochemc** [comment]
I'm sorry I'm not sure I can build a MWE for you but I'll try to give you more info. 

I use LiveServer to edit the docs of [AIBECS.jl](https://github.com/briochemc/AIBECS.jl).

**The structure** looks like

```bash
docs
├── generate.jl
├── live.jl
├── make.jl
└── src
    └── examples
        ├── example1.jl
        ├── example2.jl
        └── ....

```

I ususally run

```bash
julia --project=docs --color=yes -L docs/live.jl
```

from the root of the package directory.
And the `live.jl` file looks something like

```julia
using LiveServer

sw = LiveServer.SimpleWatcher()

# source files to check for updates to avoid infinite loop
EXAMPLEDIR = joinpath(@__DIR__, "src", "examples")
EXAMPLES_jl = [f for f in readdir(EXAMPLEDIR) if endswith(f, ".jl")]
SOURCES = [
    abspath(joinpath(@__DIR__, "make.jl"))
    abspath(joinpath(@__DIR__, "src", "index.md"))
    [abspath(joinpath(EXAMPLEDIR, example)) for example in EXAMPLES_jl]
]

append!(sw.watchedfiles, LiveServer.WatchedFile.(SOURCES))

function callback(x)
    # only trigger for source files to avoid infinite loop
    if x in SOURCES
        include(abspath(joinpath(@__DIR__, "make.jl")))
        LiveServer.file_changed_callback(x)
    end
end

callback(abspath(joinpath(@__DIR__, "make.jl"))) # make sure files exist
LiveServer.set_callback!(sw, callback)

LiveServer.serve(sw; dir = abspath(joinpath(@__DIR__, "build")), verbose=true)
```

**The issue is not systematic.** Sometimes everything is fine for multiple hours of editing. Sometimes it happens on the first change. So pretty random.

**I have not tried another editor yet**. (Sorry!) But considering how many people use vim, I would assume other people would have had the same problem if the editor was the issue, right? 

If you insist though, I will give a go at another editor. (But I cannot guarantee that the issue will happen considering how randomly it happens.)

**Comment by tlienart** [comment]
Could you try to  modify your callback  to add [these lines](https://github.com/asprionj/LiveServer.jl/blob/0bd3042da2fcb5a75577e2eb6dbe3e581ca5496c/src/utils.jl#L22-L26) and tell me whether it helped? at  the moment you don't purge the `watchedfiles` and this may ultimately be what causes issue.

(Re: VIM, yes I  was just doing guess work, likely that's not the issue)

**Comment by briochemc** [comment]
OK I will try and report back when I find the time!

FWIW, note that my `live.jl` dates from when around the time you added the Literate.jl part, so I may have to update my scripts and folder structure. I am in the process of (slowly) rewriting docs so this is the right time for me to setup the whole Documenter/LiveServer/Literate thing properly.

**Comment by tlienart** [comment]
does #89 and what you've done around it fix this issue?

**Comment by briochemc** [comment]
I think so! I fixed it on my side with the same setup as the example and it works now. (Although the issue was sporadic so I will never be 100% certain!)

Closing this now... Thanks heaps!
